
/* externs */

extern PIXCELL *pixpointer;
extern float FitPSFfwhm;
extern float FitPSFmax;
extern float FitPSFx;
extern float FitPSFy;
extern char filterSet[NUMFILTERS];
extern OBJNODE *ObjectListHead;
extern char objectListFileName[160];
extern unsigned char *RGBBuf;
extern int RGBw;
extern int RGBh;
extern unsigned char *RGBGuideBuf;
extern int RGBGuidew;
extern int RGBGuideh;
extern CCD ImagingCCD;
extern CCD SpectroCCD;
extern CCD *ccd;
extern CCDSETTINGS ccdSettings;
extern IMAGE guideImage;
//GtkWidget *queryr_dialog=NULL;
extern int MessageBoxAnswer;
extern int OverWriteDialogAnswer;
//void (*queryr_dialog_ok_function)(CCD *ccd, int *status);
extern float queryr_dialog_answer;
extern void *dummy;
extern int dataIsReady;
extern int ImageInProgress;
extern int ExitMenuItemClicked;
extern int CurrentImageWindowCloseButtonClicked;
extern char CurrentImageFileName[160];

extern int CurrentImageWindowExists;
extern int GuideFrameWindowExists;
extern int ProgressDialogExists;
extern int GuidingProgressDialogExists;
extern int SingleSettingsDialogExists;
extern int SeriesSettingsDialogExists;
extern int DarkFrameSettingsDialogExists;
extern int FlatFrameSettingsDialogExists;
extern int StackSettingsDialogExists;
extern int PickAlignStarDialogExists;
extern int OkayDialogExists;
extern int YesNoDialogExists;
extern int CameraSettingsDialogExists;
extern int OverWriteDialogExists;
extern int PlotWindowExists;

extern unsigned short LightAcquireFrame[MAXFRAMESIZE];
extern unsigned short DarkAcquireFrame[MAXFRAMESIZE];
extern unsigned short FlatLightAcquireFrame[MAXFRAMESIZE];
extern unsigned short FlatDarkAcquireFrame[MAXFRAMESIZE];

extern int DownLoadCancel;
extern int ObjectListEditable;
extern int CancelSetAlignStar;
extern int CancelCurrentAcquire;
extern int CancelCurrentGuidingAcquire;
extern int AlignStarFound;
extern int ImagingDownloadInProgress;
extern int ImagingShutterClosed;
extern int DontShowImageProgress;
extern int DontShowGuidingProgress;
extern int queueID;
extern double ScopeRA;
extern double ScopeDEC;
extern int GetScopeRADEC;

extern SINGLESETTINGS singleSettings;
extern SINGLESETTINGS singleSettings_Save;
extern SINGLESETTINGS guideImageSettings;
extern SINGLESETTINGS guideImageSettings_Save;
extern SERIESSETTINGS seriesSettings;
extern SERIESSETTINGS seriesSettings_Save;
extern DARKFRAMESETTINGS darkFrameSettings;
extern DARKFRAMESETTINGS darkFrameSettings_Save;
extern FLATFRAMESETTINGS flatFrameSettings;
extern FLATFRAMESETTINGS flatFrameSettings_Save;
extern STACKSETTINGS stackSettings;
extern STACKSETTINGS stackSettings_Save;
extern OBSSETTINGS ObsSettings;
extern OBSSETTINGS ObsSettings_Save;
extern GUIDINGSLITSETTINGS GuidingSlitSettings;
extern GUIDINGSLITSETTINGS GuidingSlitSettings_save;
extern PHOTOMETRYSETTINGS photometrySettings;
extern PLATESOLU plateSolution;
extern PLATESOLU plateSolution_save;
extern PLATESTARS plateStars;

extern bool UserStopBatch;
extern bool DontUpdate;
extern bool StartSeriesASAP;
extern bool PauseSeries;
extern bool StopSeries;
extern bool SeriesStarted;
extern bool PleaseStartSeries;
extern char binningString[3][4];

extern int SingleSaveEachDarkFrame;
extern int SeriesSaveEachDarkFrame;
extern int FlatSaveEachDarkFrame;
extern int DarkSaveEachDarkFrame;
extern int SaveEachFlatFrame;
extern int StackSaveEachDarkFrame;
extern int StackSaveEachLightFrame;
extern FLATNODE *FlatFrameHead;
extern STAR *CurrentStarList;
extern STAR *CurrentStarListSave;
extern STAR *baseStarList;
extern int CurrentStarListDefined;
extern int DoingAstrometry;
