/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_CCDAuto (void);
GtkWidget* create_UnlinkCameraQu (void);
GtkWidget* create_ExitSaveImageQu (void);
GtkWidget* create_queryr_dialog (void);
GtkWidget* create_SingleSettingsDialog (void);
GtkWidget* create_SeriesSettingsDialog (void);
GtkWidget* create_ObjectListDialog (void);
GtkWidget* create_DownLoadingDialog (void);
GtkWidget* create_SaveCurrentImageDialog (void);
GtkWidget* create_DarkFrameSettings (void);
GtkWidget* create_FlatFrameSettings (void);
GtkWidget* create_OpenFileDialog (void);
GtkWidget* create_ObservatorySettingsDialog (void);
GtkWidget* create_OverWriteDialog (void);
GtkWidget* create_StackSettingsDialog (void);
GtkWidget* create_CurrentImageWindow (void);
GtkWidget* create_PickAlignStarDialog (void);
GtkWidget* create_YesNoDialog (void);
GtkWidget* create_OkayDialog (void);
GtkWidget* create_ProgressDialog (void);
GtkWidget* create_PhotometrySettingsDialog (void);
GtkWidget* create_DefineListDialog (void);
GtkWidget* create_GuidingSlitSettingsDialog (void);
GtkWidget* create_GuideFrameWindow (void);
GtkWidget* create_GuidingProgressDialog (void);
GtkWidget* create_CameraSettingsDialog (void);
