/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gnome.h>

#include "interface.h"
#include "support.h"
#include "callbacks.h"
#include "doRoutines.h"

#define OBJECTLISTFILE "Objects.lst"  /* Text file of list of objects */
#define LONGITUDE 84.086241 /* longitude of OSUROB */
#define LATITUDE 40.721140 /* latitude of OSUROB */


/* Externs */

extern char CurrentImageFileName[16];
extern CCD ImagingCCD;
extern CCD SpectroCCD;
extern SINGLESETTINGS singleSettings;
extern SINGLESETTINGS guideImageSettings;
extern SERIESSETTINGS seriesSettings;
extern DARKFRAMESETTINGS darkFrameSettings;
extern FLATFRAMESETTINGS flatFrameSettings;
extern STACKSETTINGS stackSettings;
extern OBSSETTINGS ObsSettings;
extern PHOTOMETRYSETTINGS photometrySettings;
extern PLATESOLU plateSolution;
extern GUIDINGSLITSETTINGS GuidingSlitSettings;;
extern CCDSETTINGS ccdSettings;

GtkWidget *CCDAutoSave;

int main (int argc, char *argv[])
{
  GtkWidget *app1;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gnome_program_init (PACKAGE, VERSION, LIBGNOMEUI_MODULE,
                      argc, argv,
                      GNOME_PARAM_APP_DATADIR, PACKAGE_DATA_DIR,
                      NULL);

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */

  app1 = create_CCDAuto ();
  CCDAutoSave = app1;
  gtk_widget_show (app1);

  /* Init photometry settings */

  photometrySettings.aperatureRadius = 10.0;
  photometrySettings.zeroPoint = 25.0;
  photometrySettings.findRadius = 10.0;
  photometrySettings.minPeak = 500.0;
  photometrySettings.minFWHM = 2.0;
  photometrySettings.maxFWHM = 10.0;
  photometrySettings.autoFind = FALSE;
  photometrySettings.logResults = FALSE;
  photometrySettings.skyInnerRadius = 15.0;
  photometrySettings.skyOuterRadius = 20.0;
  photometrySettings.skySigmaCut = 3.0;
  photometrySettings.offsetSky = FALSE;
  strcpy(photometrySettings.logFileName,"photometry.log");
  photometrySettings.logFilePtr = NULL;
  photometrySettings.plotResults = FALSE;
  strcpy(photometrySettings.plotHardcopyType,"none");
  strcpy(CurrentImageFileName, "");

  /* Init Slit spectrograph guiding */

  GuidingSlitSettings.slitX0 = DEFAULTSLITX0;
  GuidingSlitSettings.slitY0 = DEFAULTSLITY0;
  GuidingSlitSettings.slitX1 = DEFAULTSLITX1;
  GuidingSlitSettings.slitY1 = DEFAULTSLITY1;
  GuidingSlitSettings.interval = 20.0;
  GuidingSlitSettings.exposure = 5.0;
  GuidingSlitSettings.XScale = 0.83;
  GuidingSlitSettings.YScale = 0.83;

  /* Init CCD Settings (type & port) */

  strcpy(ccdSettings.ImagingType,DEFAULTIMAGECCDTYPE);
  strcpy(ccdSettings.ImagingPort,DEFAULTIMAGECCDPORT);
  strcpy(ccdSettings.SpectroType,DEFAULTSPECTROCCDTYPE);
  strcpy(ccdSettings.SpectroPort,DEFAULTSPECTROCCDPORT);

  /* Init imaging ccd info structure */

  strcpy(ImagingCCD.port,DEFAULTIMAGECCDPORT);
  strcpy(ImagingCCD.name,DEFAULTIMAGECCDTYPE);
  ImagingCCD.Linked = FALSE;
  ImagingCCD.filterPosition = 6;
  ImagingCCD.Temp = 0.0;
  ImagingCCD.TempOn = FALSE;
  ImagingCCD.FanOn = FALSE;
  ImagingCCD.Image.saved = FALSE;
  ImagingCCD.Image.light_frame.active = FALSE;
  ImagingCCD.Image.dark_frame.active = FALSE;
  ImagingCCD.Image.light_frame.frame = NULL;
  ImagingCCD.Image.dark_frame.frame = NULL;
  strcpy(ImagingCCD.Image.FileName,"");
  ImagingCCD.FlatImage.saved = FALSE;
  ImagingCCD.FlatImage.light_frame.active = FALSE;
  ImagingCCD.FlatImage.dark_frame.active = FALSE;
  ImagingCCD.FlatImage.light_frame.frame = NULL;
  ImagingCCD.FlatImage.dark_frame.frame = NULL;
  strcpy(ImagingCCD.FlatImage.FileName,"");

  /* Init spectro ccd info structure */

  strcpy(SpectroCCD.port,DEFAULTSPECTROCCDPORT);
  strcpy(SpectroCCD.name,DEFAULTSPECTROCCDTYPE);
  SpectroCCD.Linked = FALSE;
  SpectroCCD.filterPosition = 6;
  SpectroCCD.Temp = 0.0;
  SpectroCCD.TempOn = FALSE;
  SpectroCCD.FanOn = FALSE;
  SpectroCCD.Image.saved = FALSE;
  SpectroCCD.Image.light_frame.active = FALSE;
  SpectroCCD.Image.dark_frame.active = FALSE;
  SpectroCCD.Image.light_frame.frame = NULL;
  SpectroCCD.Image.dark_frame.frame = NULL;
  strcpy(SpectroCCD.Image.FileName,"");
  SpectroCCD.FlatImage.saved = FALSE;
  SpectroCCD.FlatImage.light_frame.active = FALSE;
  SpectroCCD.FlatImage.dark_frame.active = FALSE;
  SpectroCCD.FlatImage.light_frame.frame = NULL;
  SpectroCCD.FlatImage.dark_frame.frame = NULL;
  strcpy(SpectroCCD.FlatImage.FileName,"");

  singleSettings.exposureTime = 1.0;
  singleSettings.whichCCD = 0;   /* 0 = imaging, 1 = tracking */
  singleSettings.binning = 0;  /* 0 = 1x1, 1 = 2x2, 2 = 3x3 */
  singleSettings.x = 0;
  singleSettings.y = 0;
  singleSettings.h = 1024;
  singleSettings.w = 1024;
  singleSettings.darkOption = 1;  /* Reuse dark frames */
  singleSettings.flatOption = 1;  /* Do not do flat fielding */
  strcpy(singleSettings.ObjectName,"");
  strcpy(singleSettings.ImageDir,"images");
  strcpy(singleSettings.DarkDir,"darks");
  strcpy(singleSettings.FlatDir,"flats");

  guideImageSettings.exposureTime = 5.0;
  guideImageSettings.whichCCD = 1;   /* 0 = imaging, 1 = tracking */
  guideImageSettings.binning = 0;  /* 0 = 1x1, 1 = 2x2, 2 = 3x3 */
  guideImageSettings.x = 0;
  guideImageSettings.y = 0;
  guideImageSettings.h = 162;
  guideImageSettings.w = 190;
  guideImageSettings.darkOption = 1;  /* Reuse dark frames */
  guideImageSettings.flatOption = 1;  /* Do not do flat fielding */
  strcpy(guideImageSettings.ObjectName,"");
  strcpy(guideImageSettings.ImageDir,"images");
  strcpy(guideImageSettings.DarkDir,"darks");
  strcpy(guideImageSettings.FlatDir,"flats");

  seriesSettings.startHours = 19.0;
  seriesSettings.duration   = 1.0;
  seriesSettings.interval   = 0.0;
  seriesSettings.startSeqNum = 0;
  strcpy(seriesSettings.objectName,"duleo");
  strcpy(seriesSettings.imageDir,"images");
  strcpy(seriesSettings.DarkDir,"darks");
  strcpy(seriesSettings.FlatDir,"flats");
  seriesSettings.filterSeq.Use[0] = FALSE; /* U */
  seriesSettings.filterSeq.Use[1] = FALSE; /* B */
  seriesSettings.filterSeq.Use[2] = FALSE; /* V */
  seriesSettings.filterSeq.Use[3] = FALSE; /* R */
  seriesSettings.filterSeq.Use[4] = FALSE; /* I */
  seriesSettings.filterSeq.Use[5] = TRUE; /* C unfiltered */
  seriesSettings.filterSeq.exposures[0] = 0.0;
  seriesSettings.filterSeq.exposures[1] = 0.0;
  seriesSettings.filterSeq.exposures[2] = 0.0;
  seriesSettings.filterSeq.exposures[3] = 0.0;
  seriesSettings.filterSeq.exposures[4] = 0.0;
  seriesSettings.filterSeq.exposures[5] = 1.0;
  seriesSettings.whichCCD = 0;   /* 0 = imaging, 1 = tracking */
  seriesSettings.binning = 0;  /* 0 = 1x1, 1 = 2x2, 2 = 3x3 */
  seriesSettings.x = 0;
  seriesSettings.y = 0;
  seriesSettings.h = 1024;
  seriesSettings.w = 1024;
  seriesSettings.darkOption = 1;  /* Reuse dark frames */
  seriesSettings.flatOption = 1;  /* Do not do flat fielding */
  seriesSettings.AutoBumpScope = FALSE;

  darkFrameSettings.numFrames = 10;
  darkFrameSettings.combineMethod = 1;  /* 1=median, 2=mean */
  darkFrameSettings.x = 0;
  darkFrameSettings.y = 0;
  darkFrameSettings.h = 1024;
  darkFrameSettings.w = 1024;
  darkFrameSettings.binning=0;       /* 0 = 1x1, 1 = 2x2, 2 = 3x3 */
  darkFrameSettings.whichCCD = 0;    /* 0 = imaging, 1 = tracking */
  darkFrameSettings.exposureTime = 1.0;
  strcpy(darkFrameSettings.imageDir,"darks");

  flatFrameSettings.numFrames = 10;
  flatFrameSettings.combineMethod = 1;  /* 1=median, 2=mean */
  flatFrameSettings.x = 0;
  flatFrameSettings.y = 0;
  flatFrameSettings.h = 1024;
  flatFrameSettings.w = 1024;
  flatFrameSettings.binning=0;       /* 0 = 1x1, 1 = 2x2, 2 = 3x3 */
  flatFrameSettings.whichCCD = 0;    /* 0 = imaging, 1 = tracking */
  flatFrameSettings.exposureTime = 1.0;
  flatFrameSettings.darkOption = 1;  /* Reuse dark frames */
  strcpy(flatFrameSettings.imageDir,"flats");
  strcpy(flatFrameSettings.DarkDir,"darks");
  flatFrameSettings.filterSeq.Use[0] = FALSE; /* U */
  flatFrameSettings.filterSeq.Use[1] = FALSE; /* B */
  flatFrameSettings.filterSeq.Use[2] = FALSE; /* V */
  flatFrameSettings.filterSeq.Use[3] = FALSE; /* R */
  flatFrameSettings.filterSeq.Use[4] = FALSE; /* I */
  flatFrameSettings.filterSeq.Use[5] = TRUE;  /* C unfiltered */
  flatFrameSettings.filterSeq.exposures[0] = 0.0;
  flatFrameSettings.filterSeq.exposures[1] = 0.0;
  flatFrameSettings.filterSeq.exposures[2] = 0.0;
  flatFrameSettings.filterSeq.exposures[3] = 0.0;
  flatFrameSettings.filterSeq.exposures[4] = 0.0;
  flatFrameSettings.filterSeq.exposures[4] = 1.0;

  stackSettings.numFrames = 6;
  stackSettings.x = 0;
  stackSettings.y = 0;
  stackSettings.h = 1024;
  stackSettings.w = 1024;
  stackSettings.binning=0;       /* 0 = 1x1, 1 = 2x2, 2 = 3x3 */
  stackSettings.whichCCD = 0;    /* 0 = imaging, 1 = tracking */
  stackSettings.exposureTime = 60.0;
  strcpy(stackSettings.imageDir,"images");
  strcpy(stackSettings.DarkDir,"darks");
  strcpy(stackSettings.FlatDir,"flats");

  /* Init the object list */

  InitObjectList("/usr/share/astro/ObjectList.lst");

  gtk_timeout_add(1000,updateStatusInfo,CCDAutoSave);

  /* Init the Observatory settings */

  strcpy(ObsSettings.name,"OSU-Lima Student Observatory");
  ObsSettings.longitude = LONGITUDE;
  ObsSettings.latitude = LATITUDE;
  ObsSettings.elevation = 80.0;
  ObsSettings.TimeZone = 8;

  gdk_rgb_init();
  gtk_main ();
  return 0;
}

