#!/bin/sh

# Upload firmware into the SBIG USB CCD cameras
#FIRMWARE=/usr/share/usb/sbigucam.hex

FLAGS=
#FIRMWARE=
LOADER=/sbin/fxload

# pre-renumeration device IDs
case $PRODUCT in

# SBIG U camera
d97/1/*) FIRMWARE=/usr/share/usb/sbigucam.hex ;;

# SBIG L camera
d97/2/*) FIRMWARE=/usr/share/usb/sbiglcam.hex ;;

# SBIG G camera
d97/3/*) FIRMWARE=/usr/share/usb/sbiggcam.hex ;;

esac

# missing firmware?
if [ ! -r $FIRMWARE ]; then
    if [ -x /usr/bin/logger ]; then
	/usr/bin/logger -t $0 "missing $FIRMWARE for $PRODUCT ??"
    fi
    exit 1
fi

# missing loader?
if [ ! -x $LOADER ]; then
    if [ -x /usr/bin/logger ]; then
	/usr/bin/logger -t $0 "missing $LOADER ??"
    fi
    exit 1
fi

if [ -x /usr/bin/logger ]; then
    /usr/bin/logger -t $0 "load $FIRMWARE for $PRODUCT to $DEVICE"
fi

$LOADER $FLAGS -I $FIRMWARE

